apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-push-image-trigger
spec:
  params:
    - name: appName
      default: flask-api
    - name: repoUrl
      default: git@github.com:Mapacherama/StrawHat_API_GraphQL_Python.git
    - name: imageUrl
      default: mapacherama/tkn-flask-api:latest # Path to api image
    - name: branchName
      default: main
    - name: dockerfile
      default: Dockerfile
    - name: pathToContext
      default: path to default flask .py file that instantiates flask
    - name: buildahImage
      default: quay.io/buildah/stable:v1.23.1
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: docker-build-push-run-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: p-buildah
        params:
          - name: appName
            value: $(tt.params.appName)
          - name: repoUrl
            value: $(tt.params.repoUrl)
          - name: imageUrl
            value: $(tt.params.imageUrl)
          - name: branchName
            value: $(tt.params.branchName)
          - name: dockerfile
            value: $(tt.params.dockerfile)
          - name: pathToContext
            value: $(tt.params.pathToContext)
          - name: buildahImage
            value: $(tt.params.buildahImage)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
          - name: ssh-creds
            secret:
              secretName: ssh-key-path
          - name: docker-config
            secret:
              secretName: docker-config-path
