apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: devsecops
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: git-strawhat-API
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
      - name: url
        value: 'https://github.com/Mapacherama/StrawHat_API_GraphQL_Python.git'
      - name: submodules
        value: 'true'
      - name: depth
        value: '1'
      - name: sslVerify
        value: 'false'
      - name: deleteExisting
        value: 'true'
      - name: verbose
        value: 'true'
      - name: revision
        value: 'clear'

  - name: python-scanner
    taskRef:
      name: bandit-scan
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
      - git-strawhat-API

  - name: kube-linter-API
    taskRef:
      name: kube-linter
    params:
    - name: subdirectory
      value: api/kubernetes/
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
      - git-strawhat-API

  - name: build-scan-API
    workspaces:
    - name: source
      workspace: shared-workspace
    taskRef:
      name: build-and-scan
    params:
      - name: out-image-name
        value: backend
      - name: CONTEXT
        value: app/
      - name: TLSVERIFY
        value: 'false'
    runAfter:
      - python-scanner
      - kube-linter-API

  - name: k8s-deploy-API
    workspaces:
    - name: source
      workspace: shared-workspace
    taskRef:
      name: apply-manifests
    runAfter:
      - build-scan-API


