apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/tekton/pipeline/persistent-volume-claim.yaml
  - base/tekton/pipeline/tekton-pipeline.yaml
  - base/tekton/tasks/task-bandit.yaml
  - base/tekton/tasks/build-task.yaml
  - base/tekton/trigger/trigger-task-web.yaml
